"""Fast exact aperture summation for Python.

``astroapers`` exposes aperture classes for readable Python workflows
and Rust-backed functions for high-throughput catalog aperture sums.
"""

from __future__ import annotations

from . import kernels
from ._apertures import (
    CircAn,
    CircAp,
    EllipAn,
    EllipAp,
    RectAn,
    RectAp,
)
from ._calibration import ParallelThresholdCalibration, calibrate_parallel_threshold
from ._containers import BoundingBox
from .kernels import (
    apsum_circ_ann_center,
    apsum_circ_ann_exact,
    apsum_circ_center,
    apsum_circ_exact,
    apsum_ellip_ann_center,
    apsum_ellip_ann_exact,
    apsum_ellip_center,
    apsum_ellip_exact,
    apsum_pill_ann_center,
    apsum_pill_ann_exact,
    apsum_pill_center,
    apsum_pill_exact,
    apsum_rect_ann_center,
    apsum_rect_ann_exact,
    apsum_rect_center,
    apsum_rect_exact,
    apsum_path_center,
    apsum_path_exact,
    apsum_wedge_center,
    apsum_wedge_exact,
    bboxes_path,
    farthest_mask_pixel,
    get_parallel_threshold,
    npix_circ_ann_center,
    npix_circ_ann_exact,
    npix_circ_center,
    npix_circ_exact,
    npix_ellip_ann_center,
    npix_ellip_ann_exact,
    npix_ellip_center,
    npix_ellip_exact,
    npix_pill_ann_center,
    npix_pill_ann_exact,
    npix_pill_center,
    npix_pill_exact,
    npix_rect_ann_center,
    npix_rect_ann_exact,
    npix_rect_center,
    npix_rect_exact,
    npix_wedge_center,
    npix_wedge_exact,
    set_parallel_threshold,
)
from ._path import PathAp
from ._pill import PillAn, PillAp
from ._wedge import WedgeAp

__all__ = [
    "BoundingBox",
    "CircAn",
    "CircAp",
    "EllipAn",
    "EllipAp",
    "kernels",
    "PillAn",
    "PillAp",
    "ParallelThresholdCalibration",
    "RectAn",
    "RectAp",
    "PathAp",
    "WedgeAp",
    "calibrate_parallel_threshold",
    "apsum_circ_ann_center",
    "apsum_circ_ann_exact",
    "apsum_circ_center",
    "apsum_circ_exact",
    "apsum_ellip_ann_center",
    "apsum_ellip_ann_exact",
    "apsum_ellip_center",
    "apsum_ellip_exact",
    "apsum_pill_ann_center",
    "apsum_pill_ann_exact",
    "apsum_pill_center",
    "apsum_pill_exact",
    "apsum_rect_ann_center",
    "apsum_rect_ann_exact",
    "apsum_rect_center",
    "apsum_rect_exact",
    "apsum_path_center",
    "apsum_path_exact",
    "apsum_wedge_center",
    "apsum_wedge_exact",
    "bboxes_path",
    "farthest_mask_pixel",
    "get_parallel_threshold",
    "npix_circ_ann_center",
    "npix_circ_ann_exact",
    "npix_circ_center",
    "npix_circ_exact",
    "npix_ellip_ann_center",
    "npix_ellip_ann_exact",
    "npix_ellip_center",
    "npix_ellip_exact",
    "npix_pill_ann_center",
    "npix_pill_ann_exact",
    "npix_pill_center",
    "npix_pill_exact",
    "npix_rect_ann_center",
    "npix_rect_ann_exact",
    "npix_rect_center",
    "npix_rect_exact",
    "npix_wedge_center",
    "npix_wedge_exact",
    "set_parallel_threshold",
]
